version: '3'

services:
  database:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    cpus: 0.50
    mem_limit: 2G
    mem_reservation: 1G
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./setup:/opt/oracle/scripts/setup
    ports:
      - 1521:1521
    environment:
      - NAME=oracle_xe
      - SHIM-SIZE=2G
      - ORACLE_PWD=development
    network_mode: bridge
