version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Development@"
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\josue.dallagnese\OneDrive\Docker\volumes\mysql:/var/lib/mysql
    network_mode: bridge