version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Admin@123"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    network_mode: bridge