version: '3'

services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    network_mode: bridge
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@domain.com.br"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "15432:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    network_mode: bridge

volumes:
  postgres:
   external: true